.
.TH "transonic" "1" "September 2011" "" ""
.
.SH "NAME"
\fBtransonic\fR \- massively-parallel ping with decent output
.
.SH "SYNOPSIS"
\fBtransonic\fR [OPTIONS] host [host ...]
.
.P
\fBtransonic\fR --help
.
.SH "DESCRIPTION"
Use transonic to ping a large number of hosts in a massively parallel way.
By default, transonic pings all hosts in parallel, using as many processes as 
there are host names on the command line. On a modern machine, this scales 
well into the thousands of machines, due to the copy-on-write mechanisms used
when fork(2)ing by the operating system kernel.
.
.P
After pinging all hosts and gathering the results, transonic displays them in 
one go, in one of several modes which can be selected on the command line.
.
.SH "OPTIONS"
.
.TP
\fB\-h\fR, \fB\-\-help\fR
Show help message and exit\.
.
.TP
\fB\-\-count\fR \fIcount\fR, \fB\-c\fR \fIcount\fR
Number of ICMP echo requests to send\.
.
.TP
\fB\-\-replies\fR \fIreplies\fR, \fB\-r\fR \fIreplies\fR
Minimum number of ping replies to expect before a host is considered up\.
.
.TP
\fB\-\-concurrency\fR \fInumber\fR, \fB\-n\fR \fInumber\fR
Number of parallel processes to use. The actual number used will be the
minimum of this and the number of hosts to ping\.
.
.TP
\fB\-\-mode\fR \fImode\fR, \fB\-m\fR \fImode\fR  
Output mode, one of cell, list or ccell\.
.
.TP
\fB\-\-terse\fR, \fB\-t\fR           
Terse output. This will not output anything except whatever the result
formatter (mode) you chose does\.
.
.TP
\fB\-\-noadjust\fR, \fB\-a\fR
Do not adjust expected number of replies, even if larger than number of
requests sent\.

.SH "DEPENDENCIES"
Since transonic does not do any of the pinging itself, it is dependant on the
output format of the ping(8) program. It currently is only tested with ping 
from the IPutils package commonly shipped with modern Linux distributions. It
may work with others or fail horribly.

.SH "PERFORMANCE"
Despite being a simple script that just uses processes for parallelism,
transonic scales surprisingly well. In experiments, it has taken less than 25 
seconds to ping 2700 hosts with 500 workers, using less than 50M of memory
doing so. For ten times that number of hosts and using twice the number of 
workers, it took less than two minutes and about 160M of RAM.
.
.P
Even so, be careful when using transonic with a huge number of hosts: while it
limits itself to using 100 processes if nothing else is specified, it will
happily try to use a million processes if told so and thus might overwhelm your
system.
.
.SH "AUTHOR"
transonic was written by Tobias Klausmann \fIklausman@schwarzvogel\.de\fR
.

